name: Man10Bank
version: 1.0
auther: [forest611]
softdepend:
  - Vault
  - Man10CommonLibs
  - Man10Mail
  - Essentials
  - Man10Score
main: red.man10.man10bank.Man10Bank
api-version: 1.21
commands:
  mbal:
    default: op
    description: /bal
  bal:
    default: op
    description: /bal
  balance:
    default: op
    description: /bal
  money:
    default: op
    description: /bal
  bank:
    default: op
    description: /bal
  atm:
    description: ATMメニューを開く
    usage: /atm
  mpay:
    description: 銀行からプレイヤーへ送金
    usage: /mpay <player> <amount>
  mcheque:
    description: 小切手（ユーザー向け）
    usage: /mcheque
  mchequeop:
    description: 小切手（運営向け）
    usage: /mchequeop
  mbaltop:
    default: op
    description: serverBalanceTop
  mloantop:
    default: op
    description: serverLoanTop
  mlend:
    default: op
    description: player loan
  pay:
    default: op
    description: vault pay
  deposit:
    description: VaultからBankへ入金
    usage: /deposit <金額|all>
  withdraw:
    description: BankからVaultへ出金
    usage: /withdraw <金額|all>
  bankop:
    default: op
    description: 管理用コマンド（ヘルスチェック/現金アイテム設定/機能オン・オフ）
  mrevo:
    description: サーバーローン管理コマンド
    usage: /mrevo
  ballog:
    description: 銀行ログ閲覧コマンド
    usage: /ballog [page]
