name: Man10Bank
version: 1.0
auther: [forest611]
softdepend:
  - Vault
  - Man10CommonLibs
  - Man10Mail
  - Essentials
  - Man10Score
main: red.man10.man10bank.Man10Bank
api-version: 1.21
commands:
  mbal:
    default: op
    description: /bal
  bal:
    default: op
    description: /bal
  balance:
    default: op
    description: /bal
  money:
    default: op
    description: /bal
  bank:
    default: op
    description: /bal
  atm:
    description: ATMメニューを開く
    permission: man10bank.user
    usage: /atm
  mpay:
    description: 銀行からプレイヤーへ送金
    permission: man10bank.user
    usage: /mpay <player> <amount>
  mcheque:
    description: 小切手（ユーザー向け）
    permission: man10bank.user
    usage: /mcheque
  mcheuqeop:
    description: 小切手（運営向け）
    permission: mchequeop
    usage: /mcheuqeop
  mbaltop:
    default: op
    description: serverBalanceTop
  mloantop:
    default: op
    description: serverLoanTop
  mlend:
    default: op
    description: player loan
  pay:
    default: op
    description: vault pay
  deposit:
    description: VaultからBankへ入金
    permission: man10bank.user
    usage: /deposit <金額|all>
  withdraw:
    description: BankからVaultへ出金
    permission: man10bank.user
    usage: /withdraw <金額|all>
  bankop:
    default: op
    description: 管理用コマンド（ヘルスチェック/現金アイテム設定）
permissions:
  man10bank.user:
    description: Man10Bankのユーザー権限
    default: true
  mchequeop:
    default: op
    description: issue money
  mcheque:
    default: op
    description: issue chheque
  mrevo:
    default: op
    description: server loan system
  ballog:
    default: op
    description: bank log
